name: Daily QQMusic Scraping

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Start local API server
        working-directory: ./qq-music-api
        run: |
          npm install
          nohup npm run dev &
          npx wait-on http://localhost:3200/getTopLists

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dependencies.txt

      - name: Run QQMusic Scraping Script
        run: python qqmusic_scraping.py
